# Generated by Django 5.0.6 on 2025-01-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
