# Generated by Django 5.0.6 on 2025-07-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMApp', '0006_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
